---
# tasks file for php

- name: Install PHP and required modules
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - php-mysqlnd
    - php-cli 
    - php-fpm
    - php-curl
    - php-xml 
    - php-mbstring

- name: Ensure PHP-FPM service is running
  service:
    name: php-fpm
    state: started
    enabled: yes

